# Data parameters
batch_size: 32
max_length: 480
num_conformations: 5

# Model parameters
hidden_size: 256
num_layers: 6
dropout: 0.1
learning_rate: 0.001
weight_decay: 0.0001

# Training parameters
epochs: 100
early_stopping_patience: 10

max_sequence_length: 480