artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1gA0dJ7JwT-_25jTOKLah3tHLq5yZBSJ8/view?usp=share_link
  local_data_file: artifacts/data_ingestion/rnn_data.zip
  unzip_dir: artifacts/data_ingestion/rnn_data

data_preparation:
  root_dir: artifacts/data_preparation
  data_dir: artifacts/data_ingestion/rnn_data
  processed_data_dir: artifacts/data_preparation/processed
  train_data_path: artifacts/data_preparation/processed/train_data.pt
  validation_data_path: artifacts/data_preparation/processed/validation_data.pt
  msa_dir: artifacts/data_ingestion/rnn_data/stanford-rna-3d-folding/MSA

model:
  root_dir: artifacts/model
  model_dir: artifacts/model/saved
  pretrained_structures_path: artifacts/model/pretrained/af3-casp16_out.pkl
  output_dir: artifacts/model/output

submission_validation:
  root_dir: artifacts/model/validation
  metrics_path: artifacts/model/validation/metrics.txt
  report_path: artifacts/model/validation/performance_report.png

visualization:
  root_dir: artifacts/visualization
  visualizations_dir: artifacts/visualization/output

web_interface:
  root_dir: artifacts/web_interface
  templates_dir: templates
  static_dir: static
  host: "0.0.0.0"
  port: 5001
  debug_mode: false
  run_server: true